name: (bump-version-release-notes-main)
run-name: "${{github.triggering_actor}} - Bump Version & Update RELEASE_NOTES.md"

on:
  workflow_dispatch:
    inputs:
      base_version_tag:
        description: "다음 버전을 계산할 기준 버전 태그"
        required: true

permissions: write-all

jobs:
  call_bump_version_release_notes:
    uses: deepx/do_workflows-central/.github/workflows/bump-release-notes.yml@main
    with:
      base_version_tag: ${{ github.event.inputs.base_version_tag }}
    secrets:
      token: ${{ secrets.GH_DCI_TOKEN }}
