name: commit-message-checker-pr
run-name: "${{github.triggering_actor}} - PR #${{ github.event.pull_request.number }} convention checker"

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions: read-all

jobs:
  commit-message-checker-pr:
    uses: deepx/do_workflows-central/.github/workflows/commit-message-checker-pr.yml@main
    secrets:
      token: ${{ secrets.GH_DCI_TOKEN }}
