name: Cppcheck Analysis

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  cppcheck:
    uses: deepx/do_workflows-central/.github/workflows/cpp-check.yml@main
    secrets:
      token: ${{ secrets.GH_DCI_TOKEN }}
      nx_user: ${{ secrets.NX_USER }}
      nx_pw: ${{ secrets.NX_PW }}
