name: release-notes-material-on-dev
run-name: "PR #${{ github.event.pull_request.number }} merged and closed - saving RELEASE_NOTES material"

on:
  pull_request:
    types: [closed]

permissions: write-all

jobs:
  call_release-notes-material-on-dev:
    name: release notes material on dev
    uses: deepx/do_workflows-central/.github/workflows/release-notes-material-on-dev.yml@main
    secrets:
      token: ${{ secrets.GH_DCI_TOKEN }}
