name: Sonar Report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 6'

jobs:
  sonar_report:
    uses: deepx/do_workflows-central/.github/workflows/sonar-report.yml@main
    with:
      project_name: dx_rt
      recipient_type: rt
      project_key: deepx_dx_rt_AZZa5znCgP_2ECN7V4UZ
      branch: dev
    secrets:
      token: ${{ secrets.GH_DCI_TOKEN }}
      sonar_rest_api_token: ${{ secrets.SONAR_REST_API_TOKEN }}
